CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50)  NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name     VARCHAR(255) NOT NULL
);

-- Default user, password is "password123"
INSERT INTO users (username, password, name)
VALUES ('admin', '$2a$10$lr2ftX8v40vkwRIhn.4ih.zlv9Lph71DpG0PAo2wBTNzvm.c9BvGq', 'Admin');