CREATE TABLE categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE transactions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount      DECIMAL(15, 2) NOT NULL,
    type        VARCHAR(10)    NOT NULL,
    description VARCHAR(255),
    date        DATE           NOT NULL,
    tag         VARCHAR(100),
    user_id     BIGINT NOT NULL REFERENCES users (id),
    category_id BIGINT NOT NULL REFERENCES categories (id)
);

INSERT INTO categories (name)
VALUES ('Alimentação'),
       ('Aluguel'),
       ('Parcelas'),
       ('Transporte'),
       ('Saúde'),
       ('Educação'),
       ('Lazer'),
       ('Outros');
